
CREATE TABLE GENDER_CODE
(
  GENDER    VARCHAR(50) NOT NULL COMMENT '성별',
  GENDER_ID VARCHAR(50) NOT NULL COMMENT '성별 ID',
  PRIMARY KEY (GENDER_ID)
) COMMENT '성별코드';

CREATE TABLE PERSONAL_INFORMATION
(
  NAME                    VARCHAR(50) NOT NULL COMMENT '이름',
  AGE                     INTEGER     NOT NULL COMMENT '나이',
  HEIGHT                  INTEGER     NOT NULL COMMENT '키',
  BLOOD_PRESSURE          INTEGER     NOT NULL COMMENT '혈압',
  MAINTENANCE_PLAN        VARCHAR(50) NOT NULL COMMENT '유지 방안',
  PERSONAL_INFO_ID        VARCHAR(50) NOT NULL COMMENT '개인 정보',
  GENDER_ID               VARCHAR(50) NOT NULL COMMENT '성별 ID',
  RE_EXAMINATION_ITEMS_ID VARCHAR(50) NOT NULL COMMENT '재검진 항목 ID',
  WEIGHT                  INTEGER     NOT NULL COMMENT '체중',
  RESULT_ID               VARCHAR(50) NOT NULL COMMENT '결과 ID',
  BLOOD_SUGAR             INTEGER     NOT NULL COMMENT '혈당',
  PRIMARY KEY (PERSONAL_INFO_ID)
) COMMENT '고객정보';

CREATE TABLE RE_EXAMINATION_ITEMS
(
  PERSONAL_INFO_ID        VARCHAR(50) NOT NULL COMMENT '개인 정보',
  RE_EXAMINATION_ITEMS_ID VARCHAR(50) NOT NULL COMMENT '재검진 항목 ID'
) COMMENT '재검진 항목';

CREATE TABLE RE_EXAMINATION_ITEMS_CODE
(
  RE_EXAMINATION_ITEMS    VARCHAR(50) NOT NULL COMMENT '재검진 항목',
  RE_EXAMINATION_ITEMS_ID VARCHAR(50) NOT NULL COMMENT '재검진 항목 ID',
  PRIMARY KEY (RE_EXAMINATION_ITEMS_ID)
) COMMENT '재검진 항목 코드';

CREATE TABLE RESULT_CODE
(
  RESULT    VARCHAR(50) NOT NULL COMMENT '검진 결과',
  RESULT_ID VARCHAR(50) NOT NULL COMMENT '검진 결과 ID',
  PRIMARY KEY (RESULT_ID)
) COMMENT '검진 결과 코드';

ALTER TABLE PERSONAL_INFORMATION
  ADD CONSTRAINT FK_GENDER_CODE_TO_PERSONAL_INFORMATION
    FOREIGN KEY (GENDER_ID)
    REFERENCES GENDER_CODE (GENDER_ID);

ALTER TABLE PERSONAL_INFORMATION
  ADD CONSTRAINT FK_RESULT_CODE_TO_PERSONAL_INFORMATION
    FOREIGN KEY (RESULT_ID)
    REFERENCES RESULT_CODE (RESULT_ID);

ALTER TABLE RE_EXAMINATION_ITEMS
  ADD CONSTRAINT FK_PERSONAL_INFORMATION_TO_RE_EXAMINATION_ITEMS
    FOREIGN KEY (PERSONAL_INFO_ID)
    REFERENCES PERSONAL_INFORMATION (PERSONAL_INFO_ID);

ALTER TABLE RE_EXAMINATION_ITEMS
  ADD CONSTRAINT FK_RE_EXAMINATION_ITEMS_CODE_TO_RE_EXAMINATION_ITEMS
    FOREIGN KEY (RE_EXAMINATION_ITEMS_ID)
    REFERENCES RE_EXAMINATION_ITEMS_CODE (RE_EXAMINATION_ITEMS_ID);
